function(automaticGameFolderOutput WILDLANDER_OUTPUT STEAM_OWRT_OUTPUT STEAM_MODS_OUTPUT LORERIM_MODS_OUTPUT LORERIM3_MODS_OUTPUT)
    if(DEFINED ENV{WILDLANDER_OWRT_FOLDER} AND IS_DIRECTORY "$ENV{WILDLANDER_OWRT_FOLDER}" AND WILDLANDER_OUTPUT)
        copyOutputs("$ENV{WILDLANDER_OWRT_FOLDER}/${PRODUCT_NAME}${PROJECT_SUFFIX}")
    endif()

    if(DEFINED ENV{SKYRIM_OWRT_FOLDER} AND IS_DIRECTORY "$ENV{SKYRIM_OWRT_FOLDER}" AND STEAM_OWRT_OUTPUT)
        copyOutputs("$ENV{SKYRIM_OWRT_FOLDER}/${PRODUCT_NAME}${PROJECT_SUFFIX}")
    endif()

    if(DEFINED ENV{SKYRIM_MODS_FOLDER} AND IS_DIRECTORY "$ENV{SKYRIM_MODS_FOLDER}" AND STEAM_MODS_OUTPUT)
        copyOutputs("$ENV{SKYRIM_MODS_FOLDER}/${PRODUCT_NAME}${PROJECT_SUFFIX}")
    endif()

    if(DEFINED ENV{SKYRIM_MODS_FOLDER2} AND IS_DIRECTORY "$ENV{SKYRIM_MODS_FOLDER2}" AND STEAM_MODS_OUTPUT)
        copyOutputs("$ENV{SKYRIM_MODS_FOLDER2}/${PRODUCT_NAME}${PROJECT_SUFFIX}")
    endif()

    if(DEFINED ENV{LORERIM_MODS_FOLDER} AND IS_DIRECTORY "$ENV{LORERIM_MODS_FOLDER}" AND LORERIM_MODS_OUTPUT)
        copyOutputs("$ENV{LORERIM_MODS_FOLDER}/${PRODUCT_NAME}${PROJECT_SUFFIX}")
    endif()

    if(DEFINED ENV{LORERIM3_MODS_FOLDER} AND IS_DIRECTORY "$ENV{LORERIM3_MODS_FOLDER}" AND LORERIM3_MODS_OUTPUT)
        copyOutputs("$ENV{LORERIM3_MODS_FOLDER}/${PRODUCT_NAME}${PROJECT_SUFFIX}")
    endif()
endfunction()
